name: Desplegar BioTrack Independiente

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias limpias
        run: |
          rm -rf node_modules package-lock.json pnpm-lock.yaml
          npm install --legacy-peer-deps

      - name: Compilar aplicacion
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
        run: npm run build

      - name: Configurar entorno de Pages
        uses: actions/configure-pages@v4

      - name: Subir paquete compilado
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Publicar en internet
        id: deployment
        uses: actions/deploy-pages@v4
